ML is the future

- genom
- satu huruf 1 byte, 
    - 2005 = 130 exabytes
    - 2010 = 1200 exabytes
    - 2015 = 7900 exabytes
    - 2020 = 40900 exabytes

Import libraries:
1. numpy : perpustakaan matematika
2. plt : merencanakan grafik yang bagus
3. pandas : pustaka terbaik untuk mengimpor dataset dan mengelola dataset


Import dataset ada 2 cara:
1. pd.read_csv('Data.csv')
2. read.csv('Data.csv')

# Importing the Dataset

In [1]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv("Y:/UDEMY\ML A-Z HandsOn Python & R in DS/Part 1 - Data Preprocessing/Section 2 -Part 1 - Data Preprocessing/Data.csv")

# Mengapa harus membuat X dan y?
# Karena kita akan bekerja dengan Numpy arrays, bukan Pandas dataframe.
# Hal ini karena Numpy arrays adalah format yang sangat cocok untuk bekerja pada data pre-processing dan membangun model ML.

# iloc = it location, menunjukkan kolom dengan indeks nya
# .values digunakan untuk mengambil hasil dari kolom indeks yang dipilih dengan data berupa Numpy array.
# .values yang membuat data X dan y menjadi Numpy arrays.

# Independent data (input features)
X = dataset.iloc[:, :-1].values
# Dependent data (Apa yang akan diprediksi?)
y = dataset.iloc[:, 3].values

In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

# Missing Data

In [4]:
# Taking care of missing data
# imputer adalah cara mengatasi missing value dengan menghubungkan data lain (misal mengambil rata-rata data)
from sklearn.preprocessing import Imputer

# artinya jika terdapat missing_value yaitu berisi 'Nan', maka hubungkan secara 'mean' dengan data lain
# mean adalah cara terbaik untuk mengatasi missing value. 
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
# method .fit() yaitu menggunakan beberapa info data dimana objeknya berlaku.
# tahap ini Imputer akan mengetahui missing_value pada kolom 1 dan 2 kemudian mengambil rata-rata kolom
imputer = imputer.fit(X[:, 1:3])
# method .transform() digunakan untuk transformasi data yang berlaku.
# tahap ini Imputer akan mengganti missing_value pada kolom 1 dan 2 dengan 'mean'.
X[:, 1:3] = imputer.transform(X[:, 1:3])

C:\Users\Ika Putri\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [5]:
# X sudah berbentuk array dan sudah tidak ada missing value
# cara kerja mean nya adalah menjumlahkan seluruh nilai yang tidak NaN, kemudian membagi dengan jumlah data yang tidak Nan.
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [6]:
# y juga sudah berbentuk array
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Categorical Data

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Encoding categorical data
# Encoding the Independent Variable
labelencoder_X = LabelEncoder()
# artinya cocokkan dan transform data X kolom 0 dengan LabelEncoder().
# tahap ini yang merubah kategori string ke integer (merubah nama negara menjadi 0, 1, 2)
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
# artinya cocokkan dan transform data X dengan OneHotEncoder().
# tahap ini merubah kolom 0 yang berupa kategorik menjadi data dummy. karena ada 3 kategori di kolom 0, maka kolom 0 di transform menjadi 3 kolom (dummy).
# tahap ini juga merubah bentuk isi kolom 1 dan 2. Misalnya 72000.0 berubah menjadi 7.2 * (10^4)
X = onehotencoder.fit_transform(X).toarray()

# Encoding the Dependent Variable
# tahap ini yang merubah kategori string ke integer (merubah 'yes or no' menjadi 0, 1)
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

C:\Users\Ika Putri\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Ika Putri\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [8]:
# X setelah di transform labelEncoder
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [10]:
# X setelah di transform OneHotEncoder
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [12]:
# y setelah di transform labelEncoder
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Split Dataset menjadi Training Set dan Test Set

- training set adalah subset dari data dimana model akan belajar bagaimana memprediksi variabel independent menggunakan variabel dependent.
- test set adalah subset dari data dimana kita akan mengevaluasi model untuk melihat apakah model yang dibangun sudah cukup baik dan bisa memprediksi dengan tepat.

In [13]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
# artinya pembagian X_train, X_test, y_train, y_test dari data X dan y, dengan rasio test set 0.2 (20%).
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
X_train

array([[1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.70000000e+01, 6.70000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.80000000e+01, 6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.50000000e+01, 5.80000000e+04]])

In [15]:
X_test

array([[1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]])

In [16]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [17]:
y_test

array([0, 0])

# Feature Scaling

Fesature Scaling adalah metode 

Ada beberapa cara Feature Scaling, yaitu:
1. Standard Scaler
    - standard scaler digunakan untuk mengansumsikan data menjadi distribusi normal pada masing-masing fitur sehingga skala distribusinya yaitu centered berada sekitar 0 dan standar deviasi bernilai 1.
    - tujuan : menjadikan data berdistribusi normal.
    - rumusnya:     
        $\frac{x_i - \text{mean($\boldsymbol{x}$)}}{\text{stdev($\boldsymbol{x}$)}}$
<img src = 1.png>

2. Min-Max Scaler
    - Min max Scaler adalah algoritma yang sangat terkenal.
    - Min Max Scaler bekerja dengan baik ketika distribusinya bukan distribusi Gaussian atau ketika standar deviasinya sangat kecil. 
    - Dimana ini akan sangat sensitif dengan outlier, sehingga mungkin dapat dipertimbangkan untuk menggunakan robust scaler.
    - Dalam hal ini, kemiringan distribusi dipertahankan, dan ketiga distribusi dibawa ke skala yang sama sehingga tumpang tindih.
    - rumusnya:     
        $\frac{x_i - \text{min}(\boldsymbol{x})}{\text{max}(\boldsymbol{x}) - \text{min}(\boldsymbol{x})}$
<img src = 2.png>
    
3. Robust Scaler
    - Robust sama halnya dengan Min-Max Scaler, bekerja dengan baik ketika distribusinya bukan distribusi Gaussian atau standar deviasinya sangat kecil.
    - Namun Robust Scaler akan menghilangkan median (pada pembilang) dan menggunakan rentang interkuartil (pada penyebut) yang akan membuat outlier tetap atau kuat.
    - Robust Scaler membawa distribusi ke skala yang sama dan tumpang tindih, sementara outlier tetap berada di luar sebagian distribusi baru. Sedangkan Max-Min Scaler, 2 distribusi normal disimpan terpisah oleh outlier yang berada di dalam kisaran 0 dan 1.
    - rumusnya:     
        $\frac{x_i - median(\boldsymbol{x})}{Q_3(\boldsymbol{x}) - Q_1(\boldsymbol{x})}$
<img src = 3.png>


Variabel dummy dapat menggunakan Feature Scaling ini jika ingin mengoptimasi akurasi dari prediksi model.
Variabel dummy tidak perlu menggunakan Feature Scaling ini jika ingin tetap menginterpretasi model dengan tepat.

In [27]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train.reshape(-1,1))

In [19]:
X_train

array([[ 1.        , -1.        ,  2.64575131, -0.77459667,  0.26306757,
         0.12381479],
       [-1.        ,  1.        , -0.37796447, -0.77459667, -0.25350148,
         0.46175632],
       [ 1.        , -1.        , -0.37796447,  1.29099445, -1.97539832,
        -1.53093341],
       [ 1.        , -1.        , -0.37796447,  1.29099445,  0.05261351,
        -1.11141978],
       [-1.        ,  1.        , -0.37796447, -0.77459667,  1.64058505,
         1.7202972 ],
       [ 1.        , -1.        , -0.37796447,  1.29099445, -0.0813118 ,
        -0.16751412],
       [-1.        ,  1.        , -0.37796447, -0.77459667,  0.95182631,
         0.98614835],
       [-1.        ,  1.        , -0.37796447, -0.77459667, -0.59788085,
        -0.48214934]])

In [20]:
X_test

array([[ 1.        , -1.        ,  2.64575131, -0.77459667, -1.45882927,
        -0.90166297],
       [ 1.        , -1.        ,  2.64575131, -0.77459667,  1.98496442,
         2.13981082]])

In [22]:
y_train

array([[ 0.77459667],
       [ 0.77459667],
       [ 0.77459667],
       [-1.29099445],
       [ 0.77459667],
       [-1.29099445],
       [-1.29099445],
       [ 0.77459667]])